# ST1131 Introduction to Statistics and Statistical Computing
## Topic 1 (Introduction to Python)

In this course, we will be using Python as our software for data manipulation, calculation and graphical display. Python has an effective data handling and storage facility, a suite of operators for calculations, a large integrated collection of packages for data analysis which includes graphical facilities, and it is a simple and effective programming language.

## Introduction

Before going into using Python for data analysis, we will first learn some basics of Python. In this course, we will use Python on VS Code through Jupyter notebooks. In a Jupyter notebook (`.ipynb`) opened in VS code, everything lives in cells, and each cell is either a Markdown cell or a Code cell ("code chunk").

**Code cells** contain actual Python that gets executed by the kernel (e.g., `venv-st1131`). When in a code cell, using `Shift+Enter` runs that cell and moves you to the next cell (Markdown or Code), while using `Ctrl+Enter` runs that cell in place. Any output appears directly beneath that cell. Variables and imports persist across cells in the same session, in the order that you run the cells, not necessarily their order on the page. You can use `Run All` to run all cells from top to bottom.

**Markdown cells** contain formatted text, not code, such as headings, bullet points, bold/italic, links, images, even LaTeX math like $x^2$. They are not executed by the kernel and are instead rendered into formatted text when you run them. They are normally used for explanations, section headers, and write-ups that sit alongside your analysis. This is what turns a notebook into a readable report rather than just a script.

Use the "`+ Code`" / "`+ Markdown`" buttons at the top or hover between cells to insert a new cell of that type.

Code cells are what the computer runs, Markdown cells are what a human reads. A well-structured notebook alternates between the two, using Markdown headers to organize the analysis and code cells to actually do it.

### Using Python as a calculator

Let's run our first code. Below you see a simple maths equation where we ask Python to run `3+5`. This uses Python as a calculator. Try running other calculations. Some outputs require us to include the `print` function to see the output. Without `print`, it might only show the last output.

In [1]:
3+5 #addition
print(3+5)

8


Below are a list of other basic operations. Order of operations follows standard math (PEMDAS/BODMAS) with parentheses overriding the order as usual. In Code cells, we can use `#` to include comments in our code. Python ignores everything after it on the same line (it is not executed). Comments are for explaining why code does something, leaving notes for yourself or others, or even temporarily disabling a line without deleting it.

In [2]:
print(10-2) #subtraction
print(10*2) #multiplication
print(10/2) #division, always returns a float even if numbers divide evenly
print(10//3) #quotient from division
print(10%3) #remainder from division
print(10**2) #exponentiation

8
20
5.0
3
1
100


### Variable assignment

We can create variables in Python which allows us to assign a value to a name (the name can only contain letters/digits/underscores, cannot contain spaces/hyphens/symbols, cannot start with a digit, cannot be a Python reserved keyword like `if`/`for`/`while`/`True`/`None`, and is case-sensitive). For example, we want `x` to be assigned the value `100`, or `abc` to be assigned whatever value that comes out from solving `9+12`. We can then call that variable for future code. For example, I want `y` to be 2 times of `x`. Try to avoid using names that match built-in functions such as `list`/`sum`/`print`, as this is allowed but it will overwrite these functions for the rest of the session.

In [3]:
x=100
abc=9+12

print(x)
print(abc)

y=2*x
print(y)

100
21
200


You can call the variable itself if done properly, which will change the value assigned to it.

In [4]:
print(x)

x=x+10

print(x)

100
110


We have been working with the data type `int` or integer. Other variable types include `float` or floating point which is a number that has both an integer and the fractional part, `str` or string which represents text, and `bool` or boolean which represents logical values (`True` or `False`).

In [5]:
a=10 #int
b=10.0 #float
c="Hello" #str, single or double quotes are usable but need to be consistent for each string
d=True #bool, either True or False

print(a,b,c,d)


10 10.0 Hello True


### List

A list is a compound data type that allows us to group values together. The values do not have to be of the same type.

In [6]:
list_1=[a,b,c,d]
print(list_1)

[10, 10.0, 'Hello', True]


### List of lists

We may want to group our data in a more meaningful way rather than just mixing up data of different types. We can create a list of lists to assist us. Sometimes, our code may be very long and it may be easier to understand our code if we write them over several lines. If it is clear that the statement isn't finished yet, Python will run the next line together.

In [7]:
list_with_labels=[["a", a],["b", b],["c", c],["d", d]]
print(list_with_labels)

list_with_labels=[["a", a], #comments here dont affect the rest below
                  ["b", b],
                  ["c", c],
                  ["d", d]]

[['a', 10], ['b', 10.0], ['c', 'Hello'], ['d', True]]


### Subsets

We can subset a list by using indexing. For example, if we want the first element from `list_1`, we can call `list_[0]`. Python's indexing starts from `0`. You can also use negative indexing to start from the back where the last element is `-1`.

In [8]:
print(list_1)
print(list_1[0])
print(list_1[2])
print(list_1[-2])

[10, 10.0, 'Hello', True]
10
Hello
Hello


### Slicing

We can also select multiple elements from a list by indicating a range instead of a singular index in the form of start:end such as `1:3`. The end is always excluded in the selection. Omitting the start index will tell Python to start from the beginning, while omitting the end index will tell Python to go to the end. The start index needs to be earlier than the end index.

In [9]:
print(list_1)
print(list_1[1:3])
print(list_1[:3])
print(list_1[1:])
print(list_1[-3:3])
print(list_1[-2:1])

[10, 10.0, 'Hello', True]
[10.0, 'Hello']
[10, 10.0, 'Hello']
[10.0, 'Hello', True]
[10.0, 'Hello']
[]


### Subsetting list of lists

Similar to subsetting a list but the first index will return a list, so we need to include a second index to return an element from that returned list.

In [10]:
print(list_with_labels)
print(list_with_labels[2])
print(list_with_labels[2][1])

[['a', 10], ['b', 10.0], ['c', 'Hello'], ['d', True]]
['c', 'Hello']
Hello


### Replacing elements in a list

You can assign new values to parts of a subset by indexing and then assigning. You can even change several at once.

In [11]:
list_1=[a,b,c,d]
print(list_1)
list_1[2]="Hello, World!"
print(list_1)
list_1[2:]=["Hello, WORLD!", False]
print(list_1)

[10, 10.0, 'Hello', True]
[10, 10.0, 'Hello, World!', True]
[10, 10.0, 'Hello, WORLD!', False]


### Extending a list

You can extend a list with another list by using `+`. This will not work with single elements.

In [12]:
list_1=[a,b,c,d]
list_3=list_1+[15, "Hi", False]
list_4=list_1+[15, "Hi", False]+[22, 25]+["World"]
print(list_1)
print(list_3)
print(list_4)

[10, 10.0, 'Hello', True]
[10, 10.0, 'Hello', True, 15, 'Hi', False]
[10, 10.0, 'Hello', True, 15, 'Hi', False, 22, 25, 'World']


### Deleting elements from a list

We can use the `del` statement to remove one or more elements. Be careful as they indices of everything else immediately changes. If you are worried about how the indices change and you have more than one to remove, you can always be creative and combine together sliced lists (take note that any sliced list that is left with one element is no longer a list and needs to be placed in a list again before joining).

In [13]:
list_1=[a,b,c,d]
print(list_1)
del list_1[2]
print(list_1)

list_1=[a,b,c,d]
list_5=list_1[0:2]+[list_1[3]] #list_1[3] is a single element and is no longer a list, so we make it into a list again by using []
print(list_5)

[10, 10.0, 'Hello', True]
[10, 10.0, True]
[10, 10.0, True]


### Caution when assigning names to items

Be careful when assinging a list to a new name. If you assign an already created list to a new name (1-to-1, without any modifications), changing any element from the new name will result in a change in the old one as well because BOTH were assigned to point to the same list. It is best to copy it explicitly. This is the same for most other data types as well.

In [14]:
old_list=[1,2,3,4,5]
new_list=old_list
new_list[0]=0
print(new_list)
print(old_list)

old_list=[1,2,3,4,5]
new_list=old_list[:]
new_list[0]=0
print(new_list)
print(old_list)

[0, 2, 3, 4, 5]
[0, 2, 3, 4, 5]
[0, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


## Functions

Python has many built-in functions which you will slowly learn over time. One example is `len` which gives you the length of a list. You can also change data types using `int`, `float`, `str`, or `bool`. Try exploring these functions to see how each data type changes to another.

In [15]:
print(list_1)
print(len(list_1))

print(int(True))
print(float(False))
print(str(True))
print(int(3.5))
print(str(3.2))
print(bool(2.7))
print(bool(0))
print(bool("Hi"))
print(bool("0"))

[10, 10.0, 'Hello', True]
4
1
0.0
True
3
3.2
True
False
True
True


### Optional arguments in functions

Some built-in functions have optional arguments that can be left blank. For example, the `sorted` function helps us to sort a list. It has an optional argument `reverse`, which by default is set to `False`, meaning that it will sort in ascending order. Setting it to `True` tells Python to sort in reverse or descending order. Use `help(sorted)` or `?sorted` to see more details of the function. You can do this for any of the built-in functions.

In [16]:
unsorted_list=[5,6,6,2,3]
sorted_list=sorted(unsorted_list)
sorted_list_r=sorted(unsorted_list, reverse=True)

print(unsorted_list)
print(sorted_list)
print(sorted_list_r)

[5, 6, 6, 2, 3]
[2, 3, 5, 6, 6]
[6, 6, 5, 3, 2]


### String and list functions

There are also functions that we can use for strings or lists respectively. Again, there are several that will you slowly learn over time. Some functions use a different syntax than previously shown. For example, the `.count()` function works with the string or list placed before the function and the element or letter we want to count as an input to the function. The `.index()` function helps us to search and get the index of the first element or letter that matches it.

In [17]:
name="aaron"
print(name.count("a"))
print(name.index("a"))

unsorted_list=[5,6,6,2,3]
print(unsorted_list.count(6))
print(unsorted_list.index(2))
unsorted_list.append(1)
print(unsorted_list)
unsorted_list.remove(6)
print(unsorted_list)

2
0
2
3
[5, 6, 6, 2, 3, 1]
[5, 6, 2, 3, 1]


## Packages

Others may have written Python functions that provide you more than just the built-in ones. To get them, we usually have to import them through packages. Packages are a directory of Python scripts or modules. They add more functions, methods, and even data types. To import packages, we first need to install them and then we can import them in our code. Install the `math` package and let's try it out. You need to include the package name together with the function when using them.

In [18]:
import math

print(math.pi)

3.141592653589793


Sometimes we do not need the full package and only need a specific part of it. We can import selectively.

In [19]:
from math import pi

print(pi)

3.141592653589793


## Numpy

We can also import packages and rename them into something shorter. There are some commonly used shortened package names such as `np` for `numpy` and `pd` for `pandas`. Let's import `numpy` so that can work with `numpy` arrays. These arrays are similar to lists previously, but they have different uses. These arrays requires homogeneity of the type of elements within them, and allows mathematical operations on them. If you mix different types of elements in the array, they will automatically be converted to a common type (such as `True` to 1 and `False` to 0). Subsetting works the same as lists.

In [25]:
import numpy as np

unsorted_list=[5,6,2,3,1]
print(unsorted_list)
unsorted_array=np.array(unsorted_list)
print(unsorted_array)
print(unsorted_array*5)
print(unsorted_array-1)

[5, 6, 2, 3, 1]
[5 6 2 3 1]
[25 30 10 15  5]
[4 5 1 2 0]


### Numpy 2D arrays

A list of lists can also be changed to a `numpy` array, but it will be 2D. They will come in the form of rows and columns.

In [21]:
print(list_with_labels)
array_with_labels=np.array(list_with_labels)
print(array_with_labels) #notice that all the items changed to str
print(array_with_labels.shape) #shows the dimensions of rows and columns
print(type(array_with_labels))

[['a', 10], ['b', 10.0], ['c', 'Hello'], ['d', True]]
[['a' '10']
 ['b' '10.0']
 ['c' 'Hello']
 ['d' 'True']]
(4, 2)
<class 'numpy.ndarray'>


Subsetting from a 2D array works differently than a list of lists. They only have one `[]` this time, but the indexes are separated by a comma where the first is the row and the second is the column.

In [22]:
print(array_with_labels[2,1])
print(array_with_labels[:,1])
print(array_with_labels[2,:])
print(array_with_labels[0:2,0])

Hello
['10' '10.0' 'Hello' 'True']
['c' 'Hello']
['a' 'b']


### Numpy functions

The package comes with several functions for basic statistics. As this is just an introduction, we will only look at some of them as examples and cover more in the future. Some examples will return `nan` if there is any missing entries in the array. It is still possible to calculate some of the functions but using a different function instead.

In [23]:
print(unsorted_array)
print(f"Mean: {np.mean(unsorted_array)}")
print(f"Median: {np.median(unsorted_array)}")
print(f"Minimum: {np.amin(unsorted_array)}")
print(f"Maximum: {np.amax(unsorted_array)}")
print(f"Range: {np.ptp(unsorted_array)}")
print(f"60th Percentile: {np.percentile(unsorted_array, 60)}")
print(f"0.6th Quantile: {np.quantile(unsorted_array,0.6)}")
print(f"Population Variance: {np.var(unsorted_array)}")
print(f"Sample Variance: {np.var(unsorted_array, ddof=1)}")
print(f"Population Standard Deviation: {np.std(unsorted_array)}")
print(f"Sample Standard Deviation: {np.std(unsorted_array, ddof=1)}")
print(f"Mean, ignoring NaN: {np.nanmean(unsorted_array)}")
print(f"Median, ignoring NaN: {np.nanmedian(unsorted_array)}")
print(f"Sample Variance, ignoring NaN: {np.nanvar(unsorted_array, ddof=1)}")
print(f"Sample Standard Deviation, ignoring NaN: {np.nanstd(unsorted_array, ddof=1)}")

[5 6 2 3 1]
Mean: 3.4
Median: 3.0
Minimum: 1
Maximum: 6
Range: 5
60th Percentile: 3.8
0.6th Quantile: 3.8
Population Variance: 3.44
Sample Variance: 4.3
Population Standard Deviation: 1.8547236990991407
Sample Standard Deviation: 2.073644135332772
Mean, ignoring NaN: 3.4
Median, ignoring NaN: 3.0
Sample Variance, ignoring NaN: 4.3
Sample Standard Deviation, ignoring NaN: 2.073644135332772


If you want to calculate row means or column means, instead of a mean over an entire 2D array, you need to include the `axis` of choice, 0 to perform down columns and 1 to perform across rows.

In [24]:
data = np.array([[10, 20, 30],
                 [40, 50, 60]])
print(data)

print(f"Overall mean: {np.mean(data)}") #overall mean

print(f"Column means: {np.mean(data, axis=0)}") #mean of columns

print(f"Row means: {np.mean(data, axis=1)}") #mean of rows

[[10 20 30]
 [40 50 60]]
Overall mean: 35.0
Column means: [25. 35. 45.]
Row means: [20. 50.]
